### ISSUE TITLE
某些文件无法下载

### ISSUE THREAD

**Issue by zibol** [Yiping-Steven/Memory_fetcher#2]
某些课程文件无法下载。上交的课程作业pdf下载之后是3KB大小的错误文件。

**Comment by Yiping-Steven** [comment]
1. 课程文件无法下载可能是因为文件太大了。我在crawler_learn.py 里有一个变量专门用来限制下载的文件大小，叫做sizeThre，默认限制1G大小的文件（考虑到有些课程会大量上传视频、大型软件等，如果允许所有文件都下载到本地硬盘的话有可能存放不下）。如果你确认本地存储空间足够的话，可以将这个阈值调到sizeThre=1000000（单位Mb），即1T大小，基本上所有文件都能下载了。

2. 上交的课程作业文件下载本没有提供这个功能，在最近一次的更新里已经加上了。
